# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SenseWeb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SenseWeb.Answer')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SenseWeb.Movie')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='recommend_movie',
            field=models.ManyToManyField(through='SenseWeb.RecommendMovie', to='SenseWeb.Movie'),
        ),
    ]
