# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SenseWeb', '0002_auto_20160110_0323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MovieGenres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SenseWeb.Genre')),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genres',
        ),
        migrations.AddField(
            model_name='moviegenres',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SenseWeb.Movie'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(through='SenseWeb.MovieGenres', to='SenseWeb.Genre'),
        ),
    ]
