# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 08:58
from __future__ import unicode_literals

import SenseWeb.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SenseWeb', '0004_auto_20160110_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quiz_type',
            field=SenseWeb.models.TinyTextField(choices=[('land', 'Landing Quiz'), ('set', 'Quiz Set')]),
        ),
    ]
